#!/usr/bin/osascript

on run argv
	set AppleScript's text item delimiters to " "
	set cmd to (argv as text)

	tell application "Terminal" to activate

	tell application "Terminal"
		tell application "System Events" to tell process "Terminal" to keystroke "t" using command down
		do script with command cmd in front window
	end tell

end run
