package net.xeger.ssh;

import java.beans.PropertyChangeListener;
import java.io.File;
import java.net.URL;

/**
 * JavaBean that contains information about an SSH session, usually as parsed
 * from the command line or launch parameters, plus some methods for interacting
 * with the session. This is an interactor (a "controller") that mediates
 * between the launchpad and the UI.
 * 
 * == Interactions with other classes UI talks to Session, and Session talks to
 * Launchpad. UI reacts to property-change events generated by Session.
 * 
 * @author Tony Spataro
 * 
 */
public interface Session {
	// //
	// // Read-only properties of the SSH session
	// //
	public String getUsername();

	public String getServer();

	public String getServerUUID();

	public String getServerName();

	public AuthMethod getAuthMethod();

	public String getSpecialPrivateKey();

	public String getSpecialPuttyPrivateKey();

	public String getPassword();

	public String getUserKeyPath();

	public URL getTroubleshootingLink();

	// //
	// // Derivatives of read-only properties
	// //
	public File getUserKeyFile();

	// //
	// // Read/write properties
	// //

	public Launcher getLauncher();

	public void setLauncher(Launcher launcher);

	// //
	// // Read/write properties
	// //

	public void launch();

	// //
	// // PropertyChangeListener support
	// //
	void addPropertyChangeListener(PropertyChangeListener listener);

	void removePropertyChangeListener(PropertyChangeListener listener);
}
